# Generated by Django 4.1 on 2022-09-05 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleCollect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("days", models.IntegerField()),
                ("city", models.CharField(max_length=128)),
                (
                    "materials",
                    models.ManyToManyField(
                        related_name="schedule_collects", to="materials.material"
                    ),
                ),
            ],
        ),
    ]
