# Generated by Django 4.1 on 2022-09-05 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telephone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=100)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info_company",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
