# Generated by Django 4.1.1 on 2022-09-12 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('reference_point', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_collect', to='companies.company')),
                ('materials', models.ManyToManyField(related_name='info_collects', to='materials.material')),
                ('user_id', models.ManyToManyField(related_name='info_collect', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
