# Generated by Django 4.1 on 2022-09-13 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("info_collects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infocollect",
            name="user_id",
            field=models.ManyToManyField(
                related_name="info_collect", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
