<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-05 12:30
=======
# Generated by Django 4.1 on 2022-09-05 12:34
>>>>>>> 39a5ad558ef4f0f01bb2f110548d0db9d5512c3c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "companies",
                    models.ManyToManyField(
                        related_name="discards", to="company.company"
                    ),
                ),
            ],
        ),
    ]
