# Generated by Django 4.1 on 2022-09-02 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("collect_days", models.PositiveIntegerField()),
                ("donation", models.BooleanField(default=False)),
                (
                    "materials",
                    models.ManyToManyField(
                        related_name="companies", to="material.material"
                    ),
                ),
            ],
        ),
    ]
